### ISSUE TITLE
Missing * in template.yml

### ISSUE THREAD

**Issue by asunar** [symphoniacloud/programming-aws-lambda-book#8]
In the book Example 5-13. SAM template for data pipeline:

`Events: s3:ObjectCreated:`

In the repo:
https://github.com/symphoniacloud/programming-aws-lambda-book/blob/335192af2b91ea2eaf59a2e2bb4ef40edc46c540/chapter5-data-pipeline/template.yaml#L38

**Comment by mikebroberts** [comment]
Nice find - thanks! We'll get that added to the list of Book Errata.

**Comment by mikebroberts** [comment]
Note added to book's errata list.
